# -*- coding: utf-8 -*-
"""Chatbot_GooglePalm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y58Q5v0DZxBxX2iBL3EDupP3WDrgjm3a
"""

!pip install pandas
!pip install langchain
!pip install tiktoken
!pip install pinecone-client
!pip install google-generativeai

!pip install -U langchain-community
!pip install pandas langchain pinecone-client google-cloud-aiplatform sentence-transformers
!pip install --upgrade google-generativeai
!pip install google-ai-generativelanguage

movies_raw = pd.read_csv("IMDB.csv")
movies = movies_raw.rename(columns={"primaryTitle": "movie_title", "Description": "movie_description"})
movies["source"] = "https://www.imdb.com/title/" + movies['tconst']
movies = movies.loc[movies["titleType"] == "movie", ["movie_title", "movie_description", "source", "genres"]]

# Step 2: Prepare the documents
movies["page_content"] = (
    "Title: " + movies["movie_title"] + "\n" +
    "Genre: " + movies["genres"] + "\n" +
    "Description: " + movies["movie_description"]
)
movies.dropna(subset=['page_content'], inplace=True)
print(movies["page_content"].head())

# Import required libraries
import pandas as pd
from langchain.document_loaders import DataFrameLoader
from langchain.chat_models import ChatGooglePalm
from langchain.prompts import PromptTemplate
from langchain.chains import RetrievalQAWithSourcesChain
from google.cloud import aiplatform
import pinecone
from sentence_transformers import SentenceTransformer
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
import os
from pinecone import Pinecone, ServerlessSpec
from google.ai import generativelanguage as genai


# Step 2: Prepare the documents
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

# Step 1: Load the CSV data

movies = movies[["page_content", "source"]]
docs = DataFrameLoader(movies, page_content_column="page_content").load()

# Step 3: Initialize Pinecone

pc = Pinecone(api_key="your_api_key")
index_name = "imdb-movies"

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
# Create or load the Pinecone index
if index_name not in pc.list_indexes():
    pc.create_index(name=index_name, dimension=384, metric="cosine", spec=ServerlessSpec(
        cloud="aws",
        region="us-east-1"))

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
from langchain.vectorstores import Pinecone
os.environ["PINECONE_API_KEY"] = "you_api_key"
vector_store = Pinecone.from_documents(
    documents=docs,
    embedding=embeddings,  # Replace with your preferred embedding model
    index_name=index_name,
)

# Step 4: Configure Google Gemini (PaLM 2)
os.environ["GOOGLE_API_KEY"] = "Google_api_key"
aiplatform.init(project="gen-lang-client-0516513741", location="us-central1")
llm = ChatGooglePalm(model="models/text-bison-001", temperature=0)

# Step 5: Define prompts
DOCUMENT_PROMPT = """{page_content}
IMDB link: {source}
========="""

QUESTION_PROMPT = """Given the following extracted parts of a movie database and a question, create a final answer with the IMDB link as source ("SOURCE").
If you don't know the answer, just say that you don't know. Don't try to make up an answer.
ALWAYS return a "SOURCE" part in your answer.

QUESTION: What's a good movie about a robot to watch with my kid?
=========
Title: A.I. Artificial Intelligence
Genre: Drama,Sci-Fi
Description: A robotic boy, the first programmed to love, David (Haley Joel Osment) is adopted as a test case by a Cybertronics employee (Sam Robards) and his wife (Frances O'Connor). Though he gradually becomes their child, a series of unexpected circumstances make this life impossible for David. Without final acceptance by humans or machines, David embarks on a journey to discover where he truly belongs, uncovering a world in which the line between robot and machine is both vast and profoundly thin.
IMDB link: https://www.imdb.com/title/tt0212720
=========
Title: I, Robot
Genre: Action,Mystery,Sci-Fi
Description: In 2035, highly intelligent robots fill public service positions throughout the world, operating under three rules to keep humans safe. Despite his dark history with robotics, Detective Del Spooner (Will Smith) investigates the alleged suicide of U.S. Robotics founder Alfred Lanning (James Cromwell) and believes that a human-like robot (Alan Tudyk) murdered him. With the help of a robot expert (Bridget Moynahan), Spooner discovers a conspiracy that may enslave the human race.
IMDB link: https://www.imdb.com/title/tt0343818
=========
Title: The Iron Giant
Genre: Action,Adventure,Animation
Description: In this animated adaptation of Ted Hughes' Cold War fable, a giant alien robot (Vin Diesel) crash-lands near the small town of Rockwell, Maine, in 1957. Exploring the area, a local 9-year-old boy, Hogarth, discovers the robot, and soon forms an unlikely friendship with him. When a paranoid government agent, Kent Mansley, becomes determined to destroy the robot, Hogarth and beatnik Dean McCoppin (Harry Connick Jr.) must do what they can to save the misunderstood machine.
IMDB link: https://www.imdb.com/title/tt0129167
=========
FINAL ANSWER: 'The Iron Giant' is an animated movie about a friendship between a robot and a kid. It would be a good movie to watch with a kid.
SOURCE: https://www.imdb.com/title/tt0129167

QUESTION: {question}
=========
{summaries}
FINAL ANSWER:"""

document_prompt = PromptTemplate.from_template(DOCUMENT_PROMPT)
question_prompt = PromptTemplate.from_template(QUESTION_PROMPT)

# Step 6: Create the RetrievalQA chain
retriever = vector_store.as_retriever()
qa_with_sources = RetrievalQAWithSourcesChain.from_chain_type(
    chain_type="stuff",
    llm=llm,
    chain_type_kwargs={
        "document_prompt": document_prompt,
        "prompt": question_prompt,
    },
    retriever=retriever,
)

question = "What's a good movie about mental health"
retriever_results = retriever.get_relevant_documents(question)
print(retriever_results)

question = "What's a good movie about an epic viking?"
response = qa_with_sources({"question": question})  # Use a direct dictionary call
print(response)